### PR TITLE
usagestats: don't save config as part of loading

### LINKED ISSUE #637: GCS:Windows:Reset GCS Config broken in Import/Export GCS Settings
next loads a incomplete config instead of deleting config and starting fresh

### PR DESCRIPTION
**Pull request by mlyle**
If so, it prevents correctly starting from a reset/fresh config.

Fixes #637, introduced in #612

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/638)

### CODE REVIEW

**Comment by PTDreamer** [comment]
lgtm

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/638#-:-KA7I9aJkZXCIZPF-kiS:677819321)_

File: ground/gcs/src/plugins/usagestatsgadget/usagestatsplugin.cpp [hunk 1]
```diff
@@ -64,12 +64,10 @@ void UsageStatsPlugin::readConfig(QSettings *qSettings, Core::UAVConfigInfo *con
     qSettings->beginGroup(QLatin1String("UsageStatistics"));
     sendUsageStats = (qSettings->value(QLatin1String("SendUsageStats"), sendUsageStats).toBool());
     sendPrivateData = (qSettings->value(QLatin1String("SendPrivateData"), sendPrivateData).toBool());
-
     //Check the Installation UUID and Generate a new one if required
-    installationUUID = QUuid(qSettings->value(QLatin1String("InstallationUUID"),"").toString());
-    if(installationUUID.isNull()){ //Create new UUID
+    installationUUID = QUuid(qSettings->value(QLatin1String("InstallationUUID"), "").toString());
+    if(installationUUID.isNull()) { //Create new UUID
```
Comment (tracernz) [inline ground/gcs/src/plugins/usagestatsgadget/usagestatsplugin.cpp]: space between if and bracket..

**Comment by tracernz** [comment]
:lgtm_strong: when Jenkins is done.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/638#-:-KA7q1PLN-cgFd1Q__md:-368342061)_
