### PR TITLE
BrainRE1: set BOR, update LEDs periodically

### LINKED ISSUE #1208: RE1 LEDs randomly wrong color
- Seen in version (release version or githash): Release 20170720.1
- On flight controller (if applicable): BrainFPV RE1

Issue details:
LEDs will be multiple colors on powerup rather than the selected color.

Example:
Color set to yellow for a bank of 8 LEDs.  On boot the first 2 were blue, 3rd magenta, next 5 yellow (I think that was the mix/order).

### PR DESCRIPTION
**Pull request by mluessi**
Sets the brown-out threshold and updates the programmable LEDs periodically. 

Status: bench tested, should be good.

Fixes #1208

### CODE REVIEW

File: flight/targets/brainre1/fw/main.c [hunk 1]
```diff
@@ -64,41 +67,41 @@ static void initTask(void *parameters);
  */
 int main()
 {
-  /* NOTE: Do NOT modify the following start-up sequence */
-  /* Any new initialization functions should be added in OpenPilotInit() */
-  PIOS_heap_initialize_blocks();
+	/* NOTE: Do NOT modify the following start-up sequence */
```
Comment (mluessi) [inline flight/targets/brainre1/fw/main.c:70]: No changes (other than the cb registration). Indentation was messed up.
