### PR TITLE
FIX: PPM timer frequency on F4 targets

### LINKED ISSUE #1091: PPM input broken (preview-20160706)
For some reason PPM is no longer working (preview-20160706). So far confirmed on Brain and BrainRE1. Maybe it's related to the recent timer/servo changes?

### PR DESCRIPTION
**Pull request by mluessi**
Tested on Brain, BrainRE1, Sparky2. On Sparky2 the PPM input timer is shared with the brushes motor outputs, so it only works if those outputs are disabled.

Fixes #1091

### CODE REVIEW

**Comment by mluessi** [comment]
jenkins, build artifacts please

File: flight/PiOS/Common/pios_servo.c [hunk 1]
```diff
@@ -161,6 +161,10 @@ void PIOS_Servo_SetMode(const uint16_t *out_rate, const int banks, const uint16_
 	TIM_TimeBaseStructure.TIM_ClockDivision = TIM_CKD_DIV1;
 	TIM_TimeBaseStructure.TIM_CounterMode = TIM_CounterMode_Up;
 	for (int i = 0; i < banks_found; i++) {
+		// Skip the bank if no outputs are configured
+		if (timer_banks[i].max_pulse == 0)
+			continue;
+
```
Comment (tracernz) [inline flight/PiOS/Common/pios_servo.c:167]: 👍

Comment (mlyle) [inline flight/PiOS/Common/pios_servo.c:167]: Because of this, should we also revert the previous sparky change?  (#1072)

Thinking about it, probably not...

What I want to do for quixote is to adapt the CC3D/Sparky things-- instead of a boolean, to specify a **timer** that should be pegged to 1MHz.  And we can make that conditional on the use of PPM/PWM.

**Comment by mlyle** [comment]
Thanks especially for troubleshooting Sparky2.

File: flight/PiOS/Common/pios_servo.c (hunk 1 above)
Comment (tracernz) [inline flight/PiOS/Common/pios_servo.c:167]: 👍

**Comment by tracernz** [comment]
So all STM32s share this frequency doubler thing for timers.. what is done differently in F4 targets?
