### PR TITLE
GCS: Upgrade to Eigen 3.3

### LINKED ISSUE #664: GCS:Libs: Upgrade to Eigen 3.3
When released (currently at beta http://eigen.tuxfamily.org). Previous versions use things that are deprecated in C++11, and cause compilation to fail with GCC 5.3 for @fujin.

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #664.

Also cleans up a bit of code in Calibration.

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

File: ground/gcs/src/plugins/config/calibration.cpp [hunk 1]
```diff
@@ -387,20 +386,21 @@ void Calibration::timeout()
...
         // Do nothing
         return;
-        break;
     case YAW_ORIENTATION:
         // Disconnect appropriate sensors
         connectSensor(ACCEL, false);
         calibration_state = IDLE;
         emit showYawOrientationMessage(tr("Orientation timed out ..."));
         emit yawOrientationProgressChanged(0);
+        break;
```
Comment (tracernz) [inline ground/gcs/src/plugins/config/calibration.cpp:395]: This looked like a bug before?

Comment (mlyle) [reply ground/gcs/src/plugins/config/calibration.cpp:395]: Ooh.  Just a bug in reported message, but still.
