### PR TITLE
GCS: Fix crash in UAVOBrowser for uint8/16

### LINKED ISSUE #1832: GCS: System>Settings>VtolPathFollowerSettings>HorzVelMax
* Seen in version (release version or githash): fee710d1 20170618 and current next
* On flight controller (if applicable): Quanton

Issue details: Clicking on default 10 m/s value causes GCS to crash. Win10.

### PR DESCRIPTION
**Pull request by tracernz**
My bad, missed a break. :blush: . Couple of other tiny improvements too.

Fixes #1832

### CODE REVIEW

File: ground/gcs/src/plugins/uavobjects/uavobjectfield.cpp [hunk 1]
```diff
@@ -1179,7 +1179,7 @@ QString UAVObjectField::getDisplayPrefix()
     case BIN:
         return QStringLiteral("0b");
     case OCT:
-        return QStringLiteral("0o");
+        return QStringLiteral("0");
```
Comment (mlyle) [inline ground/gcs/src/plugins/uavobjects/uavobjectfield.cpp:1182]: :heart:

Comment (tracernz) [reply ground/gcs/src/plugins/uavobjects/uavobjectfield.cpp:1182]: :wink:

**Comment by mlyle** [comment]
Thx for followup :D  I had just started to build to try and verify this heh
