### PR TITLE
flight: osd: fix theoretical off by one

### LINKED ISSUE #1120: OnScreenDisplay: Boot reason can write 1 byte past end of buffer
Not a real problem as long as all the reasons are shorter than the buffer but should be fixed anyway.

### PR DESCRIPTION
**Pull request by mlyle**
fixes #1120

### CODE REVIEW

File: flight/Modules/OnScreenDisplay/onscreendisplay.c [hunk 1]
```diff
@@ -727,12 +727,16 @@ void draw_alarms(int x, int y, int xs, int ys, int va, int ha, int flags, int fo
 	if (PIOS_Thread_Systime() < BOOT_DISPLAY_TIME_MS) {
 		const char *boot_reason = AlarmBootReason(alarm.RebootCause);
 		strncpy((char*)buf, boot_reason, sizeof(buf));
-		buf[strlen(boot_reason)] = '\0';
+		buf[sizeof(buf) - 2] = '\0';
 		pos = strlen(boot_reason);
 		buf[pos++] = ' ';
```
Comment (tracernz) [inline flight/Modules/OnScreenDisplay/onscreendisplay.c:732]: This will still write over the end if boot_reason is 100 or more chars long right?

File: flight/Modules/OnScreenDisplay/onscreendisplay.c [hunk 2]
```diff
@@ -727,12 +727,16 @@ void draw_alarms(int x, int y, int xs, int ys, int va, int ha, int flags, int fo
 	if (PIOS_Thread_Systime() < BOOT_DISPLAY_TIME_MS) {
 		const char *boot_reason = AlarmBootReason(alarm.RebootCause);
 		strncpy((char*)buf, boot_reason, sizeof(buf));
-		buf[strlen(boot_reason)] = '\0';
+		buf[sizeof(buf) - 2] = '\0';
```
Comment (tracernz) [inline flight/Modules/OnScreenDisplay/onscreendisplay.c:730]: Maybe I'm missing something obvious.. but why -2 rather than -1?

File: flight/Modules/OnScreenDisplay/onscreendisplay.c [hunk 3]
```diff
@@ -727,12 +727,16 @@ void draw_alarms(int x, int y, int xs, int ys, int va, int ha, int flags, int fo
...
 		pos = strlen(boot_reason);
 		buf[pos++] = ' ';
 	}
 
 	uint8_t state;
+
+	// With the above arrangement, can pass a length of 1 to this if
+	// there's an impossibly long boot reason.
+	// which then does the right thing and just fills it with a null.
 	int32_t len = AlarmString(&alarm, buf + pos, sizeof(buf) - 1 - pos,
```
Comment (tracernz) [inline flight/Modules/OnScreenDisplay/onscreendisplay.c]: This may also write past the end if boot_reason is more than 99 chars (pos = strlen(boot_reason)). Also, size_t is unsigned (~~according to Google... but I'm not sure that's correct for arm-none-eabi-gcc...~~ guaranteed by C standard) so this could go very badly if (pos + 1) is bigger than sizeof(buf)... https://github.com/d-ronin/dRonin/blob/b323ecce4bc16b80aa638fdff07793a872d2e3f7/flight/Libraries/alarms.c#L329

**Review by tracernz — CHANGES_REQUESTED** [review]
Strings in c... :/

File: flight/Modules/OnScreenDisplay/onscreendisplay.c (hunk 3 above)
Comment (tracernz) [reply flight/Modules/OnScreenDisplay/onscreendisplay.c]: https://ideone.com/V61iXx

File: flight/Modules/OnScreenDisplay/onscreendisplay.c (hunk 1 above)
Comment (mlyle) [reply flight/Modules/OnScreenDisplay/onscreendisplay.c:732]: ugh, supposed to be strlen(buf).

Then buf[98] = 0
strlen(buf)==98;
buf[98] = 0;
pos=99

File: flight/Modules/OnScreenDisplay/onscreendisplay.c (hunk 2 above)
Comment (mlyle) [reply flight/Modules/OnScreenDisplay/onscreendisplay.c:730]: Room for space.

**Comment by mluessi** [comment]
LGTM

**Review by tracernz — APPROVED** [review]

**Comment by tracernz** [comment]
I still don't super like how this whole string building works but it's better than before. :+1:
